### PR TITLE
(fix) COMMAND V on OSX

### PR DESCRIPTION
**Pull request by matrad**
issue #140

### CODE REVIEW

**Comment by andrewharvey** [comment]
Since I don't have OSX, I can't test it, so I'll leave it for someone at Mapbox to look at but I wanted to mention that according to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

> The KeyboardEvent.code property represents a physical key on the keyboard (as opposed to the character generated by pressing the key). In other words, this property returns a value which isn't altered by keyboard layout or the state of the modifier keys.

KeyV is only the character V on the QWERTY layout, so I'm not sure it can be relied on here... Have you tested what happens on other keyboard layouts?

**Comment by matrad** [comment]
@andrewharvey the osx devices mostly have the Apple-Keyboard, so for the OSX devices this will work.
On other devices I've not tested it.

But here may be other investigation needed, because this meta key can also be Windows+V on Windows-Devices:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

On OSX Devices I've tested it & it's working this way.

**Comment by andrewharvey** [comment]
Yeah but you can change your keyboard layout on OSX even with the Apple-keyboard. So on OSX using Dvorak the paste shortcut is physically Cmd+. because that's where V is.

**Comment by yapalexei** [comment]
Out of curiosity would the `_onChange` method be a better candidate for resolving this issue? because the change can be throttled/debounced just as well and accomplish a broader set of use cases.

**Comment by Grsmto** [comment]
I'm confused as on why the `paste` event is not used for this instead of hardcoded keycodes?

**Comment by andrewharvey** [comment]
The paste event is used in the upstream suggestions library.

**Comment by andrewharvey** [comment]
https://github.com/tristen/suggestions/blob/9328f1f3d21598c40014892e3e0329027dd2b538/src/suggestions.js#L41-L43

On Linux Chromium, right click paste, Ctrl+V and middle click paste all work and open the suggestions box. Happy to see a fix for OSX, but as mentioned above from KeyV isn't acceptable since on different keyboard layouts it doesn't represent paste.

**Comment by Grsmto** [comment]
Ok I took a deeper look at this and I think I get it now, thanks for your clarifications @andrewharvey 

The problem is that listening to keycodes on `keyDown` event is not a sustainable solution as it's based on device/os/browsers. My assumption is that the author didn't use the `onChange` event is because [the upstream `Suggestions` library is triggering](https://github.com/tristen/suggestions/blob/9328f1f3d21598c40014892e3e0329027dd2b538/src/suggestions.js#L178) a fake `onChange` event when user selects an address. Which would then trigger a geocode call. So author thought of using the `keyDown` event instead.

My suggestion would be to not use the `keyDown` event at all and instead either:
- use the [input event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) instead
- use the `change` event but check for `Event.isTrusted` so then we can filter out the event triggered by the `Suggestions` library

You opened this a year ago so I suppose you're not working on this anymore. Let me know if you want me to look into these solutions.

**Comment by andrewharvey** [comment]
>The problem is that listening to keycodes on keyDown event is not a sustainable solution as it's based on device/os/browsers. My assumption is that the author didn't use the onChange event is because the upstream Suggestions library is triggering a fake onChange event when user selects an address. Which would then trigger a geocode call. So author thought of using the keyDown event instead.
>
>My suggestion would be to not use the keyDown event at all and instead either:
>
>use the input event instead
>use the change event but check for Event.isTrusted so then we can filter out the event triggered by the Suggestions library

Great analysis, thank you!

>You opened this a year ago so I suppose you're not working on this anymore. Let me know if you want me to look into these solutions.

I think that's a fair assumption, I'd be keen to help review a PR with a fix if you're interested in working on it.

**Comment by andrewharvey** [comment]
closing in favour of #140 since it's not dependent on a single keyboard layout.

**Pull request closed without merging**
