### PR TITLE
Prepare 4.6.1

### PR DESCRIPTION
**Pull request by tristen**
## Release checklist

1. Create a branch off `master` and a pull request with the following changes. Copy this checklist in the comment of the pull request.
    - [x] Update the [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CHANGELOG.md) by comparing the last release and what is on `master`. In the changelog, replace the `master` heading with the to-be-released stable version.
    - [x] Update the version number in `package.json` and `package-lock.json`.
3. Request a PR review and then merge it into `master`.
4. Tag the release and start the build.
    - [ ] Make sure you've pulled in all changes to `master` locally.
    - [ ] Build the release with `npm run prepublish && npm run docs`
    - [ ] Commit and push with commit message `vX.X.X`
    - [ ] Create the git tag for the release with `git tag -a vX.X.X -m 'vX.X.X'`
    - [ ] Push the tags with `git push --tags`
    - [ ] Run `npm publish`

## Post-release checklist

Update version number in GL JS examples at [https://github.com/mapbox/mapbox-gl-js-docs](https://github.com/mapbox/mapbox-gl-js-docs):

    sed -i 's/mapbox-gl-geocoder\/v[^\/]*\//mapbox-gl-geocoder\/vX.X.X\//g' docs/pages/example/*.html

---

Ref #384

### CODE REVIEW

**Comment by andrewharvey** [comment]
Thanks @tristen does https://github.com/mapbox/mapbox-gl-geocoder/blob/master/package-lock.json#L3 also need updating?

**Comment by tristen** [comment]
> Thanks @tristen does [https://github.com/mapbox/mapbox-gl-geocoder/blob/master/package-lock.json#L3](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/package-lock.json?rgh-link-date=2020-08-15T02%3A22%3A48Z#L3) also need updating?

ohh that release step is unconventional to me. Thanks for the catch @andrewharvey

**Comment by tristen** [comment]
Hrm I was expecting the tests on this branch to go smoothly. Looks like 4 failing on coordinate precision 🤔

**Comment by andrewharvey** [comment]
> Hrm I was expecting the tests on this branch to go smoothly. Looks like 4 failing on coordinate precision thinking

I think @mapbox-danny may have fixed those in https://github.com/mapbox/mapbox-gl-geocoder/pull/385/files but because the fixes were bundled together with another feature, it's not as straightforward as just merging the fixes. 

> ohh that release step is unconventional to me. Thanks for the catch @andrewharvey

me too, maybe npm install would probably resolve it by itself if run after updating the version in package.json.

**Comment by tristen** [comment]
@andrewharvey gotcha. welp I'm tempted to close this and cut a `4.7.0` release when #385 is in.

**Comment by andrewharvey** [comment]
> @andrewharvey gotcha. welp I'm tempted to close this and cut a 4.7.0 release when #385 is in.

I'm happy either way.

**Comment by tristen** [comment]
Going to close this!

**Pull request closed without merging**
