### PR TITLE
Fixed the display of SVG icons in IE11

### PR DESCRIPTION
**Pull request by 3zzy**

### CODE REVIEW

**Comment by 3zzy** [comment]
@andrewharvey Sorry, I fixed this 5 months ago but forgot to create a PR.

**Comment by andrewharvey** [comment]
looks good, thanks. if you could fix the linting issue it should pass.

**Comment by andrewharvey** [comment]
Thanks @3zzy it should be good now, I believe it's still failing because of the way the tests run differently on forks.

**Comment by tbusser-rhm** [comment]
When I use the Geocoder I still don't get the magnifier icon in the input box. It also doesn't show when I visit this page https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ in IE11. Should this JustWork™ or am I missing something?

**Comment by 3zzy** [comment]
@tbusser-rhm The example is using 4.5.1 which doesn't include this fix (unreleased) I believe.

**Comment by tbusser-rhm** [comment]
Thanks for the quick reply @3zzy! Is there a timeframe for when a new version of the mapbox-gl-geocoder will be will released with this fix included?

**Comment by andrewharvey** [comment]
> Thanks for the quick reply @3zzy! Is there a timeframe for when a new version of the mapbox-gl-geocoder will be will released with this fix included?

I started preparing the next release in #353 but I was hoping to include #350 in that release, but I can't include #350 until there is a new mapbox-sdk-js release, which I've also prepared at https://github.com/mapbox/mapbox-sdk-js/pull/371 but I was waiting for some open PRs to be reviewed https://github.com/mapbox/mapbox-sdk-js/pulls before going ahead with that (and I can't approve my own PRs so really just need another maintainer help review).

**Comment by tbusser-rhm** [comment]
> I started preparing the next release in #353 but I was hoping to include #350 in that release, but I can't include #350 until there is a new mapbox-sdk-js release, which I've also prepared at [mapbox/mapbox-sdk-js#371](https://github.com/mapbox/mapbox-sdk-js/pull/371) but I was waiting for some open PRs to be reviewed https://github.com/mapbox/mapbox-sdk-js/pulls before going ahead with that (and I can't approve my own PRs so really just need another maintainer help review).

Thank you for taking the time to reply. I appreciate the detailed response and I hope another maintainer will find the required time to handle the reviews. Hopefully there will be a new version available in the nearby future.

**Pull request merged**
