### PR TITLE
prepare v4.6.0

### PR DESCRIPTION
**Pull request by andrewharvey**
- [x] briefly describe the changes in this PR
 - ~~[ ]~~ write tests for all new functionality
 - [x] run `npm run docs` and commit changes to API.md
 - [x] update CHANGELOG.md with changes under `master` heading before merging

### CODE REVIEW

**Comment by antony** [comment]
Looking forward to this.

Looks like Travis needs an API KEY added as a secret in order to get the build to pass again. Do you have that?

**Comment by antony** [comment]
One more thing - it might make sense to merge this PR https://github.com/mapbox/mapbox-gl-geocoder/pull/355 into this version, since it fixes a small issue with the documentation in my last PR

**Comment by andrewharvey** [comment]
- [x] rebased to include all changes from master.

regarding the failing test, that strange but I'm not sure since I don't have access to the Travis setup, someone from Mapbox will need to take a look at that.

However if you compare the travis build config https://travis-ci.com/github/mapbox/mapbox-gl-geocoder/jobs/322849232/config
```json
{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "6"
  ],
  "env": {
    "global": [
      {
        "MapboxAccessToken": ""
      }
    ]
  },
  "addons": {
    "apt": {
      "update": true,
      "packages": [
        "xvfb"
      ]
    }
  },
  "install": [
    "export DISPLAY=':99.0'",
    "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &",
    "npm install"
  ],
  "script": [
    "npm test"
  ]
}
```

with an older one that was passing https://travis-ci.com/github/mapbox/mapbox-gl-geocoder/jobs/245239959/config

```json
{
  "env": {
    "global": "MapboxAccessToken"
  },
  "addons": {
    "apt": {
      "update": true,
      "packages": [
        "xvfb"
      ]
    }
  },
  "script": [
    "npm test"
  ],
  "install": [
    "export DISPLAY=':99.0'",
    "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &",
    "npm install"
  ],
  "node_js": [
    "6"
  ],
  "language": "node_js"
}
```

there are slight differences

**Comment by antony** [comment]
Interesting, I'm no travis expert sadly - I just noticed that the failure reason was a missing API_KEY.

Once that is fixed it might shed light on some of the other changes. I guess we could ping @scottsfarley93 or @tristen to see if they are able to provide an API_KEY for testing

**Comment by tristen** [comment]
Hrm there should be an environment variable set for this in Travis:

Screen Shot 2020-04-27 at 9 46 16 PM

Defining it here doesn't look right and should probably be removed? https://github.com/mapbox/mapbox-gl-geocoder/blob/master/.travis.yml#L5

**Comment by andrewharvey** [comment]
we could wait for a mapbox-sdk-js release so we can merge https://github.com/mapbox/mapbox-gl-geocoder/pull/350 and include it in this release.

**Comment by andrewharvey** [comment]
@tristen not sure if you had time to look over this and if happy merge, tag and publish to npm? Though I just realised now we added a minor feature, so not sure if this needs to be `4.6.0` instead?

**Comment by andrewharvey** [comment]
Actually looks like the build failure actually caught a real issue this time, so I'll try to fix that first. Putting this back to draft in the meantime.

**Comment by andrewharvey** [comment]
hi @tristen looks like we have all tests passing except the flyTo once, which I suspect nothing is wrong with the code, it's just the test. I think it's okay to leave that to another PR to try and fix and not block this release.

To follow something similar to semver since this adds new functionality I bumped it to `4.6.0`. changelog updated, docs refreshed.

if you have time to do a release that would be great, but if not, no pressure.

**Pull request merged**
